<?php if ($this->pageCount>1): ?>


	<div class="paginationControl">
		<!-- Previous page link -->
		<?php if (isset($this->previous)): ?>
		<label class="numPage">
		  <a href="<?php echo $this->url(array('page' => $this->previous)) . '?' . $_SERVER['QUERY_STRING']; ?>">
		   &lt; <?php echo $this->translate('Previous'); ?></a>
		</label>
		<?php endif; ?>
	
		<!-- Numbered page links -->
		<?php foreach ($this->pagesInRange as $page): ?>
		<label class="numPage">
		  <?php if ($page != $this->current): ?>
		    <a href="<?php echo $this->url(array('page' => $page)) . '?' . $_SERVER['QUERY_STRING']; ?>">
		        <?php echo $page; ?></a>
		  <?php else: ?>
		    <?php echo $page; ?>
		  <?php endif; ?>
		</label>
		<?php endforeach; ?>
	
		<!-- Next page link -->
		<?php if (isset($this->next)): ?>
		<label class="numPage">
		  <a href="<?php echo $this->url(array('page' => $this->next)) . '?' . $_SERVER['QUERY_STRING']; ?>">
		    <?php echo $this->translate('Next'); ?> &gt;</a>
		</label>
		<?php endif; ?>
	</div>


<?php endif; ?>